const titles = [
    'Title 1',
    'Title 2',
    'Title 3',
    '   Title 4',
    'PLAYER_WINS_AGAINST_HIGHER_POSITION_CLUB',
    'PLAYER_WINS_AGAINST_HIGHER_POSITION_CLUB',
    'PLAYER_WINS_AGAINST_HIGHER_POSITION_CLUB',
    'PLAYER_WINS_AGAINST_HIGHER_POSITION_CLUB',
    'PLAYER_WINS_AGAINST_HIGHER_POSITION_CLUB',
    'PLAYER_WINS_AGAINST_HIGHER_POSITION_CLUB',
    'PLAYER_WINS_AGAINST_HIGHER_POSITION_CLUB',
    'PLAYER_WINS_AGAINST_HIGHER_POSITION_CLUB',
    'PLAYER_WINS_AGAINST_HIGHER_POSITION_CLUB',
    'PLAYER_WINS_AGAINST_HIGHER_POSITION_CLUB',
    'PLAYER_WINS_AGAINST_HIGHER_POSITION_CLUB',
    'PLAYER_WINS_AGAINST_HIGHER_POSITION_CLUB',
    'PLAYER_WINS_AGAINST_HIGHER_POSITION_CLUB',
    'PLAYER_WINS_AGAINST_HIGHER_POSITION_CLUB',
    'PLAYER_WINS_AGAINST_HIGHER_POSITION_CLUB',
    'PLAYER_WINS_AGAINST_HIGHER_POSITION_CLUB',
]

export default titles;