const titles = [
    'PLAYER_WINS_AGAINST_HIGHER_POSITION_CLUB',
    'PLAYER_WINS_AGAINST_HIGHER_POSITION_CLUB',
    'PLAYER_WINS_AGAINST_HIGHER_POSITION_CLUB',
    'PLAYER_WINS_AGAINST_HIGHER_POSITION_CLUB',
    'PLAYER_WINS_AGAINST_HIGHER_POSITION_CLUB',
    'PLAYER_WINS_AGAINST_HIGHER_POSITION_CLUB',
    'PLAYER_WINS_AGAINST_HIGHER_POSITION_CLUB',
    'PLAYER_WINS_AGAINST_HIGHER_POSITION_CLUB',
    'PLAYER_WINS_AGAINST_HIGHER_POSITION_CLUB',
    'PLAYER_WINS_AGAINST_HIGHER_POSITION_CLUB',
    'PLAYER_WINS_AGAINST_HIGHER_POSITION_CLUB',
    'PLAYER_WINS_AGAINST_HIGHER_POSITION_CLUB',
    'PLAYER_WINS_AGAINST_HIGHER_POSITION_CLUB',
    'PLAYER_WINS_AGAINST_HIGHER_POSITION_CLUB',
    'PLAYER_WINS_AGAINST_HIGHER_POSITION_CLUB',
    'PLAYER_WINS_AGAINST_HIGHER_POSITION_CLUB',
    'PLAYER_WINS_AGAINST_HIGHER_POSITION_CLUB',
    'PLAYER_WINS_AGAINST_HIGHER_POSITION_CLUB',
    'PLAYER_WINS_AGAINST_HIGHER_POSITION_CLUB',
    'PLAYER_WINS_AGAINST_HIGHER_POSITION_CLUB',
]

export default titles;